### ISSUE TITLE
Dataset Folder Structure

### ISSUE THREAD

**Issue by ChinmayRai** [kvsphantom/instrument-recognition-polyphonic#1]
Could you elaborate on how did you get the Dataset in the desired folder structure (as suggested in settings.py) ?
The MedleyDB dataset does not have any train/test split, but the settings.py tries to mention paths for 
MEDLEY_TRAIN_FEATURE_BASEPATH, MEDLEY_TEST_FEATURE_BASEPATH. 
The Dataset that I got from MedleyDB website has following structure:
V1
V1/sound_track_name
V1/sound_track_name/sound_track_name_RAW
V1/sound_track_name/sound_track_name_RAW/{multiple_RAW files}
V1/sound_track_name/sound_track_name_STEMS
V1/sound_track_name/sound_track_name_STEMS/{multiple_STEM files}
V1/sound_track_name/sound_track_name_MIX.wav

So you can see that I have only _RAW, _STEMS and _MIX wav files. The MedleyDB suggets the installation of a python library called 'medleydb' for annotations and metadata.

So can you tell whether we need to set the PATHS in settings.py before running data_prep.py ?
If so then how do we get the data set into desired structure ?
If not then I think that data_prep.py expects a different structure of dataset.

Conclusively I want to know what needs to been done between downloading the dataset and running data_prep.py ?

Thanks in advance

**Comment by vskadandale** [comment]
Hi Chinmay, you are right, MedleyDB does not have train/test split partitions. In this work, I am trying to improve the instrument recognition performance achieved by  [Li et al.](https://arxiv.org/pdf/1511.05520.pdf). Since, we are comparing the performance numbers, we decided to use the same train/test partitions as used by the reference paper. In fact, our code to arrive at the train/test partitions, borrows heavily from the [code](https://github.com/glennq/instrument-recognition) published along with the same reference paper for data preprocessing. Note that our reference paper uses only the window-hop configuration 1s_h100 (1 second non-overlapping  windows). For this configuration, our reference paper reported the partitions of 21177 (train) and 4985 (test). However, we followed their source code but ended up with 21476 (train) and 4686 (test) for the window-hop configuration 1s_h100. We did not investigate this difference in numbers further, but they sum up to 26162 (= 21177+4985 = 21476+4686) in both the cases. The code in ./data_prep/gen_split.py does the split of dataset into training and testing components. 

In our work (also in Li et al. 2015), we consider the MIX.wav files. We do not use the stems and raw files.  When I had published this code, MedleyDB Original (2014) was used. The annotations and metadata were provided along with the wav files at that time. Our PATH_TO_DATASET='/homedtic/vshenoykadandale/dataset/MedleyDB'
The following were the contents of the folder /homedtic/vshenoykadandale/dataset/MedleyDB:
----Audio
   |-Folders
     |- folder_name_METADATA.yaml
     |- folder_name_MIX.wav
     |- folder_name_RAW
     |- folder_name_STEMS
----Annotations
   |-Instrument_Activations
   |-Melody_Annotations
   |-Pitch_Annotations
   |-Stem_Intervals
   |-Stem_Rankings

To start implementing the code (as is), you only need to specify the dataset path such that this folder has same folder structure as above. During the time, I published the code, the medleyDB scripts were not available.

By the way, I have also shared the manuscript of my [master's thesis](https://github.com/kvsphantom/instrument-recognition-polyphonic/blob/master/Venkatesh_SMC_THESIS.pdf) if you need more details.

**Comment by ChinmayRai** [comment]
Thanks for your Reply. It really helped.
